import {
  NextPage,
  GetStaticProps,
  GetStaticPaths,
  GetServerSideProps,
} from "next"
import Head from "next/head"
import Document from "next/document"
import Image from "next/image"
import styles from "../styles/Home.module.css"

/* Import mui */
import { useTheme } from "@mui/material/styles"
import { makeStyles } from "@mui/styles"
import {
  useMediaQuery,
  Typography,
  Button,
  Paper,
  Grid,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Box,
  Container,
} from "@mui/material"
import Carousel from "react-material-ui-carousel"
import "@fontsource/moo-lah-lah"

/* Import Component */
import HeaderBar from "src/components/HeaderBar"
import HorizontalImageList from "src/components/HorizontalImageList"
import GridList from "src/components/GridList"
import CarouselMUI from "src/components/CarouselMUI"
import CarouselGridMUI from "src/components/CarouselGridMUI"

const useStyles = makeStyles((theme) => ({
  headerBar: {
    background: "red",
  },
  font: {
    fontfamily: "Moo Lah Lah",
  },
  font2: {
    fontfamily: "Lora",
  },
}))

interface HomeProperty {
  dogData?: any
  dogImageList?: []
}

var items = [
  {
    name: "Random Name #1",
    description: "Probably the most random thing you have ever seen!",
  },
  {
    name: "Random Name #2",
    description: "Hello World!",
  },
]

const Home: NextPage<HomeProperty> = ({ dogData, dogImageList }) => {
  const classes = useStyles()
  const theme = useTheme()
  const xsMedia = useMediaQuery(theme.breakpoints.down("xs"))
  return (
    <div>
      <Box sx={{ width: "100%", height: "100%" }}>
        <Head>
          <title>Create Next App</title>
          <meta
            name="description"
            content="Generated by create next app, width=device-width, initial-scale=1.0"
          />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Lora&display=swap"
            rel="stylesheet"
          ></link>
        </Head>

        <HeaderBar />

        {/* <Box sx={{ mx: 10, backgroundColor: "primary.dark" }}>
          <CarouselMUI itemList={dogImageList}></CarouselMUI>
        </Box> */}

        <Box sx={{ position: "relative", m: 5, height: 300 }}>
          <img
            src="https://source.unsplash.com/user/c_v_r"
            alt="https://source.unsplash.com/user/c_v_r"
            style={{
              width: "100%",
              height: "300px",
              objectFit: "cover",
              borderRadius: "25px",
              position: "relative",
            }}
          />
          <div
            style={{
              backgroundColor: "yellow",
              position: "absolute",
              top: "50%",
              left: "50%",
              transform: "translate(-50%, -50%)",
            }}
          >
            Centered
          </div>
          <Typography
            variant="h5"
            color="initial"
            style={{
              position: "absolute",
              bottom: "20px",
              right: "20px",
              backgroundColor: "yellow",
              color: "white",
              paddingLeft: "20px",
              paddingRight: "20px",
            }}
          >
            good
          </Typography>
        </Box>

        <Box sx={{ mx: 10, backgroundColor: "primary.dark" }}></Box>

        {/* <CarouselGridMUI itemList={dogImageList}></CarouselGridMUI> */}

        {/* <Typography
          className={classes.headerBar}
          variant="body1"
          color="initial"
          align="center"
        >
          good
        </Typography> */}

        {/* <HorizontalImageList></HorizontalImageList> */}

        {/* Use "textAlign to center Button" */}
        <Box sx={{ textAlign: "center" }}>
          <Button
            variant="contained"
            onClick={async () => {
              console.log(dogImageList)
              // const headers = {
              //   "x-api-key": "e10cdc7a-3fa2-4945-b892-f9514812a1a4",
              // }
              // const data = await fetch(
              //   "https://api.thedogapi.com/v1/images/hMyT4CDXR",
              //   { headers }
              // ).then(async (response) => await response.json())
            }}
          >
            get api data
          </Button>
        </Box>

        {/* <GridList itemList={dogImageList}></GridList> */}

        {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </Box>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const headers = {
    "x-api-key": "e10cdc7a-3fa2-4945-b892-f9514812a1a4",
  }
  const dogData = await fetch(
    "https://api.thedogapi.com/v1/breeds?attach_breed=0&limit=20",
    { headers }
  ).then(async (response) => await response.json())
  // console.log(data)

  const dogImageList = dogData.map((item: any) => {
    return item.image
  })
  // console.log(imageList)

  //return multiple parameter
  return {
    props: { dogData, dogImageList },
  }
}

export default Home
