import {
  NextPage,
  GetStaticProps,
  GetStaticPaths,
  GetServerSideProps,
} from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

/* Import mui */
import { useTheme } from "@mui/material/styles"
import { makeStyles } from "@mui/styles"
import {
  useMediaQuery,
  Typography,
  Button,
  Grid,
  Card,
  CardActions,
  CardContent,
  CardMedia,
  Box,
} from "@mui/material"

/* Import Component */
import HeaderBar from "src/components/Header"
import HorizontalImageList from "src/components/HorizontalImageList"
import GridList from "src/components/GridList"

const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "100%",
  },
  headerBar: {
    background: "red",
  },
}))

interface HomeProperty {
  dogData?: any
  dogImageList?: []
}

const Home: NextPage<HomeProperty> = ({ dogData, dogImageList }) => {
  const classes = useStyles()
  const theme = useTheme()
  const matches = useMediaQuery(theme.breakpoints.down("xs"))
  return (
    <div className={classes.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderBar />

      <Typography
        className={classes.headerBar}
        variant="body1"
        color="initial"
        align="center"
      >
        good
      </Typography>

      <HorizontalImageList></HorizontalImageList>

      <Button
        variant="contained"
        onClick={async () => {
          console.log(dogImageList)
          // const headers = {
          //   "x-api-key": "e10cdc7a-3fa2-4945-b892-f9514812a1a4",
          // }
          // const data = await fetch(
          //   "https://api.thedogapi.com/v1/images/hMyT4CDXR",
          //   { headers }
          // ).then(async (response) => await response.json())
        }}
      >
        get api data
      </Button>

      <GridList itemList={dogImageList}></GridList>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const headers = {
    "x-api-key": "e10cdc7a-3fa2-4945-b892-f9514812a1a4",
  }
  const dogData = await fetch(
    "https://api.thedogapi.com/v1/breeds?attach_breed=0&limit=20",
    { headers }
  ).then(async (response) => await response.json())
  // console.log(data)

  const dogImageList = dogData.map((item: any) => {
    return item.image
  })
  // console.log(imageList)

  //return multiple parameter
  return {
    props: { dogData, dogImageList },
  }
}

export default Home
