import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

/* Import mui */
import { useTheme } from "@mui/material/styles"
import { makeStyles } from "@mui/styles"
import { useMediaQuery, Typography } from "@mui/material"

/* Import Component */
import HeaderBar from "../src/components/Header"
import HorizontalImageList from "../src/components/HorizontalImageList"

const useStyles = makeStyles((theme) => ({
  root: {
    width: "100%",
    height: "100%",
  },
  headerBar: {
    background: "red",
  },
}))

const Home: NextPage = () => {
  const classes = useStyles()
  const theme = useTheme()
  const matches = useMediaQuery(theme.breakpoints.down("xs"))
  return (
    <div className={classes.root}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderBar />

      <Typography
        className={classes.headerBar}
        variant="body1"
        color="initial"
        align="center"
      >
        good
      </Typography>

      <HorizontalImageList></HorizontalImageList>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
